title: alakhkaushik
description: AWS Certified | Solution Architecture | Software Architecture | Cloud Architecture | System Integration
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
