title: alakhkaushik
description: AWS Certified | Cloud Architecture | Software Architecture | System Integration
logo: /assets/img/profile.jpg
show_downloads: true
google_analytics: G-PWZQ7DCP37
theme: jekyll-theme-cayman
